### ISSUE TITLE
how can i  authorized the api visor supervisord

### ISSUE THREAD

**Issue by hare2011** [php-api-clients/supervisord#1]
my supervisord config is setted username and password.
at you example have not authorized .
how can i authorized i api to access the supervisord.

**Comment by WyriHaximus** [comment]
Hey @hare2011 I'll add an example soon detailing how to authenticate against a supervisor configured with [those settings](http://supervisord.org/configuration.html#inet-http-server-section-settings).

**Comment by WyriHaximus** [comment]
Right so I released [`1.1.0`](https://github.com/php-api-clients/supervisord/releases/tag/1.1.0) with build in support for this
